### ISSUE TITLE
Сделать Dockerfile под развертку скриптов заверителей

### ISSUE THREAD

**Issue by ghost** [u-transnet/core-lab#6]
Сделать Dockerfile под развертку python скриптов заверителей из репозитория на git

**Comment by ghost** [comment]
BLOCK [#23067074](https://wallet.bitshares.eu/block/23073772) 150UTDEV.SKILL до утра 30.12.2017

**Comment by ghost** [comment]
[Репозиторий](https://github.com/u-transnet/witness-scripts) под скрипты заверителей
[Dockerfile](https://github.com/u-transnet/dockerfiles/blob/master/utransnet-witness/Dockerfile) развертывающий Python3, python-utransnet и запускающий основной скрипт `run.py`

**Comment by cptn-solo** [comment]
@mparkhomenko огонь. Спасибо. Надо готовить теперь комплект для сборки, с инструкцией, для развертывания ноды сети. Причем не уверен, что [тестнет](https://github.com/u-transnet/Gateway/projects/2#card-6351319) важнее, чем дать ход какому-то варианту ранней версии генезиса u-transnet [(ближайшие планы команды)](https://github.com/u-transnet/info/issues/49)

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #23396631
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV
