### ISSUE TITLE
SPIKE: Разобраться с реализацией atomic swap в decred/scorum

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/core-lab#7]
Пришли из #5 

Нужно изучить [реализацию atomic swap](https://github.com/Scorum/Scorum/wiki/How+to+do+atomicswap) scorum, причем у них есть пример scorum-lightcoin, который ссылается на [реализацию decred](https://github.com/decred/atomicswap/), анонсированную не так давно

На выходе нужно получить:
- описание предполагаемой реализации AS с сетью Bitcoin с примерами кода (ссылки на строки репозиториев, используемых в качестве референсов для своего дизайна)
- описание реализации желательно готовить в формате, схожем с [exchage_bot](https://github.com/u-transnet/codebase/tree/exchange_bot) ([задача](https://github.com/u-transnet/codebase/issues/42))

**Comment by ishmelev23** [comment]
@kkrupovich 
БЛОК #23795911

ПЕРЕВОД |  
-- | --
От | superpchelka23
Кому | utd-front
Количество | 62.50000 UTDEV.SKILL

смотрим 24 января 2018 вечером

**Comment by ishmelev23** [comment]
[Схема atomic swap](https://www.draw.io/?lightbox=1&target=blank&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Atomic%20Transaction#R7Vzdk6I4EP9rrNp90ILw6aOft1u3d7dV83B3TxYDUblF42EcnfvrL4GA%2BWJEB3Rnxq0tBjuQhO5O%2F7o7DR1rtDr8kgab5W8ogkkHGNGhY407AJg2cMkfSnnOKZ5r5YRFGkfsoiPhIf4PMqLBqLs4glvhQoxQguONSAzReg1DLNCCNEV78bI5SsRRN8ECKoSHMEhU6p9xhJc51Qfekf4FxotlMbLp9vOWxyD8sUjRbs3G6wBrnv3Lm1dB0Rd70O0yiNCeI1mTjjVKEcL52eowggnlbcG2%2FL5pRWs57xSucZ0bmJyegmQHixm7Cbl1OEekBzJB%2FMyY4v67Q0VDd5uJbEAuMJ3N4dhIzhbZ37HR6U87Y7PjG%2FR86GRHOztOs%2BMkOw65czc7%2Btlx1AHkv5H14GVHwK4EWYd9g7vdzy4ws3ODXUCI7EqTG8I8tuajsLmR2ydsFHaBUUyYfwR%2BFDdYbciTrh%2B3m%2FzBk5wB05xzjA%2BMHMVPMumVDBZ7CVGCUqGXTPMMx3BO3nvhDAYzyswhPVY9ei0OlbKq8UQG%2BUfXkjoXcOYsLhllmI1yjtiryRqFaF5HKGtBTdYSZSH%2FNA%2F97Y%2FRr6Mvg6%2B%2FZ5K%2Bmki5cV%2BQ7TlcBgInAYYHSl%2FiVUIIJjnd4hT9gCM2yzVaQzr3OEkkUpDEizX5GRIjCwl9%2BARTHBP0GLCGVRxFdJjhfhlj%2BLAJQjrmnmAloWXoAKn9Ncpp0Q7godKGmyUyEMSFaAVx%2BkwuYTcAg4HJswii%2ByNy2TajLTnU8hgtYGC5KHs%2BAgY5YZihxw%2BvEj941p%2B21%2BXP3Ex7HFpkrdSIU%2BvcqxAuHWHAdTAuIKO03vlxIBr5sQgZU87O87AFuJ5tbr4qupV0UCw%2B3doWFlFIOsxtqTQl0bS%2BpMqcDvPqSle1H8IwVHSbtDz6ju00pIGmpIGW5SgqWGopr4JuAypoAo0OSgwibtaGnsarzPHjF728djHacNRvwSNMvqNtjGNEWx8RxmhFLkhow7D09niW5%2F6eNcwGG2w3uYNKWR0UP%2BbxgVqAIZvPeIkx9WwH9KHBNIzWZi8mvu08JpYi7YVkRKIAAQ7IH0rfUouXQpjExB6BqUWZFSRBupoRDzbFszBB4Y8ZfCLimy3jLUbp82wbLmG0S%2BAMxys42wc4XHZN4Pc260UTNsgSNcA2VQ3Q2SC7CQWwVAWo5SFql3u5gofc7Xxr9gjBdvlpC8MU4s%2Byv8lcy9wC2YXlKIcYHY2a73Jzm4izKn%2BeY9Xo0dK7vaxJWhciFunQqtq0RA70I1tnWnzwaLluO6bFuappcWqZljyCoxyMiF6U7DzHsyBcc6izbhSmhbM5iptRaZT0tqwwfqvDgkbrPTSfxyHsEfXdpTF%2B7mXGYh%2Fj5ewHJHaCkRsSn%2BOctAtWW3ZBF9xK0oPraEDzBZTNSbDdxqEoOHiI8V%2Fc%2Bd9Utj2nZA6MlESCxBoyHNqlYXGVpWcXxw5Hw46ClsIkwPGTOKSOR2yE7yjOPO%2BKxeS6jthFPlV2F582kDpyPGlVyh3hIF1ArHSUiax87FpSLDIlnBRF6%2Fte3XpThlRXXTq%2BRldAA0unmC3HdOo2UEthvl%2BOK06MhuM6J6YRjtfzYu9QUyk9t%2FADS09BjYPbghqguqAfw0g5vi8y3VeZ3pqRstUlU5nv5XPREy6oL71%2FcpxKXr4Qj8uxhMf5%2Bo4SAwxEv19KFAy4FMGYu9Lk%2FPjRRQGAmFA5K61xPB91zktxHIerzmM0GHjcJqfhasCgtcAD1Ag8ru265svtVq6r1RfF4VkXuq6uLNd%2Be65rXyPF8xL7AFQl9gcWl9LgV7hTmRZ%2FryDkOpJINSBUrF5eNa0GVqqlespVGXAVlz541jvbT5OnJG7lXZb1jgLoz7UI4YY%2BfJw35Pt4Ym7Dc66IEFa9eOGe9W4z6%2B0Zogb4muRkW1lvS%2BP93gPG8wLG09JrK2C01NzkBwkYJT%2FO96%2BX1bLU3eoiq6WDrE9US49Zryn4%2FNEqCxT7phFWWwkxW1NaUGtXz%2BJ8k7Hi2vhcSG5xrZkIs8WniPPtbZKZGjm15onYvsIxGlo%2BsJ8oxUu0QOsgmRypkqpqotY8Ui3i1qxlTSbGNdGfRds%2FEONnVkYa7DAipOO43xCFmlw6JB7iZDCdZjVP9SNiVQKv3ZFxRckpRTl1w9qTHTUX1tqasLbufvs9B9d6Dq46qmrSrt0kwjKN%2FhUNW5FVuKdvWt7olDaTTVNTwdhW%2FsbR5W%2FOzLRWoUqJZQ1lYHPDe6sMrCutxTJJfS5UAakmxDTlnprDKkeTJqmFVYCrAVPfVxhXY9W5%2BbiGQOIlu28ojyk9UQZ1LAOZ%2B8XZ07XjEd8GOYCm8Kg95NBs3%2BgzwKX74nGCHopuiqHWHwo3Mh1Q1WzM9cwrHv%2BejS%2Fq3uRMVSwLDpv1VN6R4lneNRWvRsnb208K0lTgBqarmEAxTQtX5qWLeYv4TMCZQE5DOUQFFTWht9lXpd1EEtFRUyQV6%2Bbn8BVvJyXZ47DA9RJZjq9Zk7mLv90E6xNbhG%2FSFakuA3m9K1IGRwLzXgUUJ%2FSyovqkSl9brkqRNNm%2BakSsK2i4w0t7hsvsS%2BJ2NFVIbcGLq%2BY%2F7vCilZIvSck1rgcvbr194LdVCGCfLASAXUJewTSEXUrqbqlaTulexPTreo7KTX7FrJSCb1EhPEOqii2qhPidZc2qLWiv0gd97HnhW2nTivDwgrfS7jZDVBEgqoin5jyL3GTjhv0eJV4bxsVXE4CmUqw1FL8HiXVRXBKSxrNuDcR1MeL7B%2FF9nEJ62p2nEHafSL8o7RaNeX1fFN0Wyl1XeqvIdmstXbMBKPc0G5CVWYLLX2Z%2FcUOE21a%2FxH9o8K32JlPBV6nKkVPBfVeF%2BNZCde8eFvx0YYHpeaJCeKotaSss8O5hwZtwQuRaCANcLy7wanghZ9ZCSLy5pMLuOtUNirGWXwurXd1gn%2BioueIG%2F7zaFaa9NYRVxnvmG5CcXbhaxZLxDOMy0Sk9yQVGzYmur7p24of23qhZZDW4pq9ql1Rs22jGta8aybZCtb666MRPFb4%2FyVG5TacNxVOmcTPJAY25rPWBSmoV1W%2BOEpc3pq8xPuwJw5v6HOxZU1Dqe9R66qI4OvfI3sEHM38aTbaA5Kp5jq3osja%2Bu0CZyc%2FjR6FzvDl%2Bedua%2FA8%3D).
Следующим постом будет разбор реализации Atomic Swap с помощью [decred](https://github.com/decred/atomicswap).

**Comment by ishmelev23** [comment]
Разбор на примере Atomic Swap в Bitcoin, все остальные реализации сделаны по аналогии, они различаются только адресом api к которому они подключаются.

Предположим Алиса и Боб имеют адреса A1 и B1 в BLOCKCHAIN1, A2 и B2 в BLOCKCHAIN2.
Atomic Swap в данной реализации состоит из нескольких шагов:
1. Генерация Secret Алисой.
2. Создание контракта CT1 с адресом ADR_CT1 на перевод средств с адреса A1 на B1 требующий для осуществления транзакции Secret Алисы или возврат средств на счет A1 по истечению timelock1.
3. Осуществление транзакции: перевод средств с A1 на адрес ADR_CT1 (резервирование средств) с именем TR1.
4. Отправка hash(Secret), TR1 и CT1  Бобу.
5. Аудит транзакции Бобом.
6. Создание контракта CT2 с адресом ADR_CT2 на перевод средств с адреса B2 на A2 требующий для осуществления транзакции Secret Алисы или возврат средств на счет B2 по истечению timelock2.
7. Осуществление транзакции: перевод средств с B2 на адрес ADR_CT2 (резервирование средств) с именем TR2.
8. Отправка TR2 и CT2  Алисе.
9. Аудит транзакции Алисой.
10. Вывод средств Алисой с помощью Secret. Он добавляется в скрипт для разблокировки средств CT2 как вход для транзакции на вывод средств OUT_TR2.
11. Боб извлекает Secret из скрипта разблокировки, который использовался в транзакции OUT_TR2.
12. Боб использует Secret, чтобы вывести средства с помощью CT1.
-------------------
Однако есть другая ветка событий, если истекает timelock1 и timelock2, то Алиса и Боб могут вернуть себе средства соответственно. timelock2 < timelock1, что стимулирует Алису (инициатора Atomic Swap) совершить перевод как можно раньше и если она его не совершит, будет наказана тем, что ей придётся ждать больше времени, чтобы вернуть средства.

В следующем посте будут примеры кода

**Comment by ishmelev23** [comment]
Применительно к нашему проекту нам необходимы следующие компоненты из данной реализации:
1. [initiateCommand ](https://github.com/decred/atomicswap/blob/master/cmd/btcatomicswap/main.go#L729) - инициализация Atomic Swap, которая состоит из следующих шагов: 
- создание контракта;
- создание и рассылка транзакции на перевод средств на счет скрипта (резервирование);
- создание транзакции на возврат средств.
2. [participateCmd](https://github.com/decred/atomicswap/blob/master/cmd/btcatomicswap/main.go#L775) - создание ответного контракта на основе Hash(Secret): фактически все действия совпадают с пунктом 1, единственное отличие, что timelock == 24 часа vs 48 часов в 1 случае.
3. [redeemCmd](https://github.com/decred/atomicswap/blob/master/cmd/btcatomicswap/main.go#L812) - создаётся и публикует транзакцию на вывод средств, как вход он указывает адрес контракта со средствами и скрипт разблокировки средств, как выход счет на который будут перечислены средства.
4. [refundCmd](https://github.com/decred/atomicswap/blob/master/cmd/btcatomicswap/main.go#L906) - команда для возврата средств, генерирует и исполняет транзакцию, которая переведет средства, если timelock истёк.
5. [auditContractCmd](https://github.com/decred/atomicswap/blob/master/cmd/btcatomicswap/main.go#L967) - проверяет контракт на корректность: в действительности ли транзакция на перевод средств ссылается на указанный контракт, а так же выводит информацию по контракту.

**Comment by ishmelev23** [comment]
Что необходимо нам реализовать для проведения Atomic Swap:
1. подключение к api кошелька для Bitcoin для работы скрипта выше;
2. резервирование средств с помощью hash(Secret) на том же объекте. Доступ к средствам должен открываться только с помощью Secret. После разблокировки и выполнения транзакции на перевод средств Secret должен быть отражен в блокчейне и привязан к этой транзакции;
3. timelock. Блокировку которая не позволит отменить резервирование из п.2 в течении определенного промежутка времени;
4. возможность получить в рамках блокчейна доступ к объекту на котором заблокированы средства и проверить его состояние и соответствующие аттрибуты.
----------------------------
Из всех этих компонентов можно составить api аналогичный реализованному в decred, однако очевидно, что придётся дорабатывать ядро graphene, т.к. он не поддерживает скрипты и контракты.

**Comment by cptn-solo** [comment]
BLOCK #23828630


TRANSFER |  
-- | --
From | utd-front
To | superpchelka23
Quantity | 62.50000 UTDEV

Спасибо, @netral23 

Предлагаю потратить еще день скилла и посмотреть, что реализовано на стороне блокчейна scorum - там внутри - steemit, а это тоже графен. Заодно сможешь погрузиться в анализ графена и его транзакций.

**Comment by ishmelev23** [comment]
БЛОК #23842210


ПЕРЕВОД |  
-- | --
От | superpchelka23
Кому | utd-front
Количество | 62.50000 UTDEV.SKILL

Разобраться в реализация Scorum. Задача до 14:00 26 января
Результат: отчет по способу реализации Atomic Swap в Scorum.

**Comment by ishmelev23** [comment]
**Сводка по проекту Scorum**

**Краткое описание результата**: Atomic Swap реализован при доработке ядра и использовании вместо стандартной БД от graphene, базы [chainbase](https://github.com/scorum/scorum/tree/develop/libraries/chainbase) и добавления новых[объектов-сервисов](https://github.com/scorum/scorum/tree/develop/libraries/chain/services), которые выполняют необходимые для Atomic Swap процедуры.

Сначала будет описана общая структура проекта, а потом будут ссылки на код и объяснения, каким образом реализован Atomic Swap.

----
**Общее описание проекта** 
Конкретно нас интересует фрагмент связанный с ядром, потому будут рассмотрены внутренности папки [libraries](https://github.com/scorum/scorum/tree/develop/libraries)

**app** - нода и необходимые для её функционирования компоненты.
**chain** - собственно сам БЧ ([database](https://github.com/scorum/scorum/blob/develop/libraries/chain/database.cpp)), а именно логика его работы и такие важные компоненты, как [сервисы ](https://github.com/scorum/scorum/tree/develop/libraries/chain/services) использование которых будет описано позже.
**chainbase** - замена стандартной БД от graphene, судя по всему не их разработка, вероятно в своё время было форкнуто [отсюда](https://github.com/GolosChain/chainbase)
**egenesis** - утилиты для инициализации БЧ, его генезис
**fc** - библиотека для поддержки client-server взаимодействия
**net** - реализация client-server взаимодействия, а именно доступа к ноде
**plugins** - судя по всему это слушатели операций и в принципе компоненты несущие доп. функционал на нодах, которые производят действия до и после отработки операции
**protocol** - основные базовые компоненты graphene и собственно scorum (такие как transaction, asset, block и т.п.)
**scheme** - пока не нашел, где применяется
**sidechain** - видимо закладка на будущее в сторону разработки sidechain
**utilities** - наборы вспомогательных процедур
**wallet** - соответственно кошелек, который подключается к ноде и взаимодействуют через jsonrpc

----
**Реализация Atomic Swap** 
Реализация построена не базовыми средствами платформы (как допустим сделал bitcoin построив atomic swap немного расширив свой скриптовый язык), а с помощью доработки ядра.
Как новые программные компоненты добавлены [операции](https://github.com/scorum/scorum/blob/develop/libraries/protocol/scorum_operations.cpp) и [сервисы](https://github.com/scorum/scorum/tree/develop/libraries/chain/services) связанные с Atomic Swap.
Исполнители регистрируются на ноде и являются обработчиками операций.
Ниже будет описан процесс обработки операции, для примеры был взят atomicswap_initiate:
1) В кошельке пользователь инициирует Atomic Swap, эта операции прикрепляется к транзакции и рассылается, [сссылка на код](https://github.com/scorum/scorum/blob/develop/libraries/wallet/wallet.cpp#L2680);
2) При [добавлении блока в БЧ ](https://github.com/scorum/scorum/blob/develop/libraries/chain/database.cpp#L531) происходит [обработка ](https://github.com/scorum/scorum/blob/develop/libraries/chain/database.cpp#L1840) всех транзакций блока.
3) При обработке транзакции [перебираются и применяются](https://github.com/scorum/scorum/blob/develop/libraries/chain/database.cpp#L2016) все операции, что были в неё записаны.
4) Для каждой операции [вызывается](https://github.com/scorum/scorum/blob/develop/libraries/chain/database.cpp#L2030) свой исполнитель (это [обёртка ](https://github.com/scorum/scorum/blob/develop/libraries/chain/evaluators/scorum_evaluators.cpp#L1414) вокруг сервиса), который выполняет все необходимые операции.

**Подводя итог:** 
С помощью кастомной логики происходят необходимые для Atomic Swap операции, т.е. это обычный программный код удовлетворяющий требованиям Atomic Swap, который придерживается общей структуры проекта graphene.

**Comment by cptn-solo** [comment]
BLOCK #23881976

TRANSFER |  
-- | --
From | utd-front
To | superpchelka23
Quantity | 62.50000 UTDEV

Спасибо, @netral23 , будем думать, куда двигаться дальше. @mparkhomenko @netral23 @codename-art , ваше мнение тоже приветствуется.

**Comment by cptn-solo** [comment]
@netral23 
> c помощью доработки ядра.

Да, т.к. 1 графен == 1 смарт-контракт

> Исполнители регистрируются на ноде и являются обработчиками операций.

не понял, что за исполнители регистрируются на ноде. evaluators? А как они регистрируются на ноде, можно в двух словах?

> При обработке транзакции перебираются и применяются все операции, что были в неё записаны.

Операции в других блоках (ранних) - так же попадают в обработку? Или операции одной транзакции не могут быть в разных блоках? Я правильно понимаю, что на определенном этапе мы ищем исходную операцию (или ее транзакцию с операцией?), в которой хранится секрет? Мы зависим от реализации БД хранящей блоки? По-моему где-то в чатах видел, что в этом и состоит разница между ядром steemit (scorum) и Bitshares - в steemit цепь хранится в БД, в Bitshares - считывается в память. Правда, есть [реализация](https://github.com/bitshares/bitshares-core/wiki/ElasticSearch-Plugin) плагина для использования Elastic search для Bitshares (что-то связанное с историей транзакций), не знаю, как это связано с БД и поможет ли это как-то.

**Comment by ishmelev23** [comment]
@kkrupovich 

> не понял, что за исполнители регистрируются на ноде. evaluators? А как они регистрируются на ноде, можно в двух словах?

Да evaluators. Ну не совсем на ноде, они [регистрируются ](https://github.com/scorum/scorum/blob/develop/libraries/chain/database.cpp#L1538) на инстансе БД при её [открытии](https://github.com/scorum/scorum/blob/develop/libraries/chain/database.cpp#L100), а открывается она на [при запуске ноды](https://github.com/scorum/scorum/blob/develop/libraries/app/application.cpp#L374).

------------

> Операции в других блоках (ранних) - так же попадают в обработку? Или операции одной транзакции не могут быть в разных блоках? Я правильно понимаю, что на определенном этапе мы ищем исходную операцию (или ее транзакцию с операцией?), в которой хранится секрет? Мы зависим от реализации БД хранящей блоки?

Они просто сделали так, что контракты хранятся как записи в БД вроде аккаунтов.
Ниже приведу основные операции над контрактами, которые вызываются из сервисов:
1) [Получение контракта](https://github.com/scorum/scorum/blob/develop/libraries/chain/services/atomicswap.cpp#L35)
2) [Перевод средств](https://github.com/scorum/scorum/blob/develop/libraries/chain/services/atomicswap.cpp#L110)
3) [Возврат средств](https://github.com/scorum/scorum/blob/develop/libraries/chain/services/atomicswap.cpp#L132)
4) [Создание контракта](https://github.com/scorum/scorum/blob/develop/libraries/chain/services/atomicswap.cpp#L47)

Такой же подход используется при [создании аккаунтов](https://github.com/scorum/scorum/blob/develop/libraries/chain/services/account.cpp#L603).

А теперь самый интересный момент, ссылки на исходники в BitShares:
1) [Создание аккаунта](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/account_evaluator.cpp#L186).
2) [Обработка транзакций в блоке](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L511).
3) [Перебор всех операций](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L617).
4) [Применение операций](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_block.cpp#L642).
5) [Регистрация evaluator](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_init.cpp#L130).

--------------------

Для реализации нам необходимо:
1) реализовать операции связанные с Atomic Swap;
2) evaluator;
3) сущность (index, как я понял) в БД, которая будет представлять контракт;
4) добавить синхронизацию новой сущности с остальными нодами;

Однако я не рассмотрел момент, как происходит синхронизация БД в BitShares, я видел как происходит синхронизация блоков из БЧ, а вот как именно доп. информация такая аккаунты, заверители и т.п. синхронизируется пока не смотрел.

**Comment by cptn-solo** [comment]
@netral23 полагаю, мы уходим в #8 ?

**Comment by ishmelev23** [comment]
[Переход к проектированию и реализации](https://github.com/u-transnet/transnet-core/projects/1)
