### ISSUE TITLE
SPIKE: Исследовать работу базы данных graphene и посмотреть существующие оптимизации с помощью elasticsearch

### ISSUE THREAD

**Issue by ishmelev23** [u-transnet/core-lab#8]
Пришли из #7 

**Описание**: Исследовать работу базы данных graphene, которая входит в состав [bitshares-core](https://github.com/bitshares/bitshares-core), и посмотреть существующие оптимизации с помощью elasticsearch.

**Цель**: Разобрать поиск объекта с информацией по идентификатору из операции с этим объектом на примере аккаунта, для дальнейшей разработки аналогичной объекта представляющего контракт для Atomic Swap.

**Результат**: Отчет со ссылками на код и последовательное объяснение работы поиска объекта с информацией + описание применения elasticsearch со ссылками на участки кода.

**Comment by ishmelev23** [comment]
БЛОК #23971273

От | superpchelka23
-- | --
Кому | utd-front
Количество | 62.50000 UTDEV.SKILL


SPIKE: Исследовать работу базы данных graphene и посмотреть существующие оптимизации с помощью elasticsearch. Предоставление результатов 31.01.18 вечер

**Comment by ishmelev23** [comment]
База данных в graphene представляет собой набор данных в памяти, которые [организуются с помощью boost::multi_index::multi_index_container](https://github.com/bitshares/bitshares-core/blob/master/libraries/db/include/graphene/db/index.hpp#L63), который позволяет быстро проводить поиск по 1-му или нескольким параметрам в массиве.
Каждый index реализует методы для [загрузки ](https://github.com/bitshares/bitshares-core/blob/master/libraries/db/include/graphene/db/index.hpp#L226) и [выгрузки ](https://github.com/bitshares/bitshares-core/blob/master/libraries/db/include/graphene/db/index.hpp#L247) данных с диска.
Индексы [хранятся ](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_init.cpp#L177) в инстансе БД.

Иерархия индексов следующая:
1) [index ](https://github.com/bitshares/bitshares-core/blob/master/libraries/db/include/graphene/db/index.hpp#L68) - класс определяющий основной интерфейс для индексов, а именно операции создания, удаления, модифицирования, поиска, получения, вставки;
2) [generic_index ](https://github.com/bitshares/bitshares-core/blob/master/libraries/db/include/graphene/db/generic_index.hpp#L43) - класс реализующий базовые команды индекса, обобщая их на входной multi_index_container;
3) [primary_index ](https://github.com/bitshares/bitshares-core/blob/master/libraries/db/include/graphene/db/index.hpp#L202)(и base_primary_index, который описывает основной интерфейс для primary_index) - фактически это обёртка вокруг generic_index (или какого-либо другого), который сюда передаётся как DerivedIndex, а так же реализация основных операций по взаимодействию с диском (выгрузка, загрузка и т.п.)

---------

Как в целом работает БД:
1) При открытии [БД загружается с диска ](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_management.cpp#L159)
2) Если база оказалась пустой (нет компонента описывающего глобальные переменные БЧ), тогда [запускается генезис](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_management.cpp#L163)
3) При закрытии БД все данные [выгружаются на диск](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_management.cpp#L210) и после БД закрывается

---------

Как происходит синхронизация второстепенных сущностей
Для создания каждой сущности есть операция, которая обязательно включена в одну из транзакций. Таким образом при обмене блоками между пирами синхронизируются и второстепенные сущности.

---------

ElasticSearch
Применяется просто для разгрузки ноды и хранения некоторых данных в сторонней БД, что поможет проводить более сложный анализ данных, что следует из [описания их проекта](https://github.com/bitshares/bitshares-core/projects) на GitHub.
Сейчас фактически реализован экспериментальный плагин, который сохраняет историю операций с аккаунтом в elasticsearch. 
Судя по [их планам](https://github.com/bitshares/bitshares-core/projects/1) ElasticSearch планируется применяться для аналитики состояния БЧ (т.е например проводить анализ транзакций, состояние счетов и т.п.), а не как замена текущей БД.

**Comment by cptn-solo** [comment]
@netral23 резюмирую 
- базу данных пока не переделываем. Пускай будет в памяти. Просто следим за ситуацией. 
- архитектура решения понятна, необходимые изменения - тоже, поэтому
- надо начинать формулировку задач и искать исполнителей  `TBD`. 
- исходим из:

> @netral23 
Смотри тут есть 2-е стороны

1) Делаем через ES:
Минусы: придётся решать вопрос с синхрнизации с БЧ;
Плюсы: будет хранится не в основной БД;
2) Делаем через обычную БД:
Минусы: всё опять в памяти;
Плюсы: поидее должно работать быстрее, реализации по аналогии с остальными объектами;

Теперь главный вопрос, а так ли нам нужен ES? Если рассматривать его как главный аналог основной БД, то это отдельная и длительная тема. Если он чисто для контрактов, то думаю тут надо исходить из оценки потребляемого объёма памяти (а тут я думаю сильно больше чем другие сущности они не будут занимать), а так же необходимых запросов для получения доступа к контрактам (в данном случае если рассматривать только реализацию свопов, то ES будет лишними телодвижениями, т.к. поиск контрактов не будет сложный по логике)

Если будем накручивать аналитику, то это отдельная тема.

**Comment by cptn-solo** [comment]
@netral23 спасибо!
BLOCK #24030920

TRANSFER |  
-- | --
From | utd-front
To | superpchelka23
Quantity | 62.50000 UTDEV
